name: my-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action actions/checkout@v2
      - name: setup JAVA JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          SECRET_CODE_CLIMATE: ${{secrets.SECRET_CODE_CLIMATE}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          
