name: my-check

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: setup JAVA JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: 7.4.2
          arguments: build
          build-root-directory: app
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          SECRET_CODE_CLIMATE: ${{secrets.SECRET_CODE_CLIMATE}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          
